version: '3.4'
services:
  api:
    command: 'bash -c "rm -f tmp/pids/server.pid && bundle config unset frozen && bundle && rails db:create && rails db:migrate && rails db:seed && sleep 100d"'
    init: true
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
      - "9003:9003"
    depends_on:
      - db
    volumes:
      - '.:/kube'
    stdin_open: true
    tty: true
    environment:
      DATABASE_HOST: db
      DATABASE_USER_NAME: root
      DATABASE_NAME: kube
      DATABASE_USER_PASSWORD: test#1234
      RAILS_ENV: development
  db:
    image: mysql:8
    init: true
    volumes:
      - ".datastore/mysql-data:/var/lib/mysql"
    environment:
      MYSQL_DATABASE: kube
      MYSQL_USER: root
      MYSQL_PASSWORD: test#1234
      MYSQL_ROOT_PASSWORD: test#1234
    ports:
      - "3306:3306"
  phpmyadmin:
    image: phpmyadmin:5
    init: true
    environment:
      PMA_HOST: db
      PMA_PMADB: kube
      PMA_USER: root
      PMA_PASSWORD: test#1234
    ports:
      - "8080:80"

  redis:
    init: true
    image: "redis:7"
    command: "redis-server --requirepass ragasiyam"
    volumes:
      - ".datastore/redis-data:/data"
    ports:
      - "6379:6379"
